# Generated by Django 3.2.6 on 2022-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Data1', models.CharField(max_length=50)),
                ('Data2', models.CharField(max_length=50)),
            ],
        ),
    ]
